trojan-gfw/igniter

- app/src/main/cpp/CMakeLists.txt
REQUIRES https://github.com/trojan-gfw/libn2t/pull/2
> libn2t/lwip: rework file structure

- app/src/main/cpp/CMakeLists.txt
> Add android log for libn2t

- app/src/main/java/io/github/trojan_gfw/igniter/MainActivity.java
> use try-with-resources statement to be elegant

- app/src/main/java/io/github/trojan_gfw/igniter/TrojanService.java
sync vlan4 and vlan6 ip address, netmask and route with shadowsocks-android
add google ipv6 dns server
shutdown service when onDestroy() is called
> add ipv6 support

- app/src/main/AndroidManifest.xml
- app/src/main/java/io/github/trojan_gfw/igniter/MainActivity.java
- app/src/main/java/io/github/trojan_gfw/igniter/ProxyService.java
- app/src/main/java/io/github/trojan_gfw/igniter/TrojanService.java
- app/src/main/res/values/strings.xml
To preview:
https://github.com/oasiscifr/igniter/releases/tag/v0.1.0-clash-3
Now igniter won't display wrong state(switches and buttons) when the activity is destroyed and recreated.
> sync UI/service state with BroadcastReceiver

- .circleci/config.yml
- app/src/main/java/io/github/trojan_gfw/igniter/ProxyService.java
pumping data in golang native world
**NOTE:** Need https://github.com/trojan-gfw/igniter-go-libs/pull/3
> use nonblocking tun fd again

- .circleci/config.yml
> CircleCI: update golibs with clash v0.17.1

- .circleci/config.yml
> CircleCI: update go-tun2socks with latest lwip commit

- app/src/main/java/io/github/trojan_gfw/igniter/MainActivity.java
- app/src/main/java/io/github/trojan_gfw/igniter/ProxyService.java
- app/src/main/java/io/github/trojan_gfw/igniter/TestConnection.java
* fix leak
* use proxy when test
> fix: test connection

- app/src/main/java/io/github/trojan_gfw/igniter/MainActivity.java
- app/src/main/java/io/github/trojan_gfw/igniter/TestConnection.java
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/menu/menu_main.xml
- app/src/main/res/values/strings.xml
- add a bar menu and an item for testing connection
- remove the testing button
> Change the main UI.

- app/src/main/java/io/github/trojan_gfw/igniter/exempt/contract/ExemptAppContract.java
- app/src/main/java/io/github/trojan_gfw/igniter/exempt/fragment/ExemptAppFragment.java
- app/src/main/java/io/github/trojan_gfw/igniter/exempt/presenter/ExemptAppPresenter.java
- app/src/main/res/menu/menu_exempt_app.xml
- app/src/main/res/values/strings.xml
Add search field on Toolbar of ExemptAppFragment. Now it's easier to find app to exempt.
> Exempt app optimization

- app/src/main/java/io/github/trojan_gfw/igniter/MainActivity.java
- app/src/main/res/values/strings.xml
Detect trojan url from Clipboard and fill into the EditText.
> Clipboard import

- app/src/main/java/io/github/trojan_gfw/igniter/MainActivity.java
- app/src/main/java/io/github/trojan_gfw/igniter/exempt/data/AppInfo.java
- app/src/main/java/io/github/trojan_gfw/igniter/exempt/presenter/ExemptAppPresenter.java
1. Fix the NullPointerException caused by calling `clipboardText.toString()` when `clipboardText` is null.
2. Search app name case-insensitivly in ExemptAppPresenter.
> Bugfix branch

- app/src/main/java/io/github/trojan_gfw/igniter/MainActivity.java
fix: https://github.com/trojan-gfw/igniter/issues/205
> Fix: crash because of clipboard

- app/src/main/java/io/github/trojan_gfw/igniter/TrojanHelper.java
- app/src/main/java/io/github/trojan_gfw/igniter/servers/data/ServerListDataManager.java
Add some null checks to prevent weird NullPointerException in `ServerListDataManager#saveServerConfig(TrojanConfig)`
> Null checks in ServerListDataManager

- app/src/main/res/layout/activity_main.xml
> Fix soft keyboard popup problem

- app/src/main/java/io/github/trojan_gfw/igniter/Globals.java
- app/src/main/java/io/github/trojan_gfw/igniter/MainActivity.java
- app/src/main/java/io/github/trojan_gfw/igniter/ProxyService.java
- app/src/main/java/io/github/trojan_gfw/igniter/common/utils/FileUtils.java
- app/src/main/java/io/github/trojan_gfw/igniter/exempt/activity/ExemptAppActivity.java
- app/src/main/java/io/github/trojan_gfw/igniter/exempt/contract/ExemptAppContract.java
- app/src/main/java/io/github/trojan_gfw/igniter/exempt/data/ExemptAppDataManager.java
- app/src/main/java/io/github/trojan_gfw/igniter/exempt/data/ExemptAppDataSource.java
- app/src/main/java/io/github/trojan_gfw/igniter/exempt/fragment/ExemptAppFragment.java
- app/src/main/java/io/github/trojan_gfw/igniter/exempt/presenter/ExemptAppPresenter.java
- app/src/main/res/values/strings.xml
Check external config file existence in ExemptAppPresenter, migrate it if necessary. Also migrate it implicitly in MainActivity only if READ_EXTERNAL_STORAGE permission is granted.
> Save exempt app list config in internal storage

- app/src/main/java/io/github/trojan_gfw/igniter/MainActivity.java
- app/src/main/java/io/github/trojan_gfw/igniter/ProxyService.java
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/root_preferences.xml
add multi language for Simplified Chinese
> Multi language zh

- app/src/main/java/io/github/trojan_gfw/igniter/Globals.java
- app/src/main/java/io/github/trojan_gfw/igniter/MainActivity.java
- app/src/main/java/io/github/trojan_gfw/igniter/TrojanConfig.java
- app/src/main/java/io/github/trojan_gfw/igniter/TrojanHelper.java
- app/src/main/java/io/github/trojan_gfw/igniter/common/constants/ConfigFileConstants.java
- app/src/main/java/io/github/trojan_gfw/igniter/servers/contract/ServerListContract.java
- app/src/main/java/io/github/trojan_gfw/igniter/servers/fragment/ServerListFragment.java
- app/src/main/java/io/github/trojan_gfw/igniter/servers/presenter/ServerListPresenter.java
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/menu/menu_server_list.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
1. add server/node name. not support Trojan URL
2. export config list to file and save in document directory.
> export-config-list

- app/src/main/java/io/github/trojan_gfw/igniter/servers/contract/ServerListContract.java
- app/src/main/java/io/github/trojan_gfw/igniter/servers/data/ServerListDataManager.java
- app/src/main/java/io/github/trojan_gfw/igniter/servers/data/ServerListDataSource.java
- app/src/main/java/io/github/trojan_gfw/igniter/servers/data/TrojanConfigWrapper.java
- app/src/main/java/io/github/trojan_gfw/igniter/servers/fragment/ServerListAdapter.java
- app/src/main/java/io/github/trojan_gfw/igniter/servers/fragment/ServerListFragment.java
- app/src/main/java/io/github/trojan_gfw/igniter/servers/presenter/ServerListPresenter.java
- app/src/main/res/layout/item_server.xml
- app/src/main/res/menu/menu_server_list.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
Due to the inconvenience of profile deletion, now delete buttons in ServerListFragment are removed. Instead, batch deletion feature is implemented. Now it is much simpler to delete all servers and import new configuration.
> Profile list batch delete feature

- app/src/main/AndroidManifest.xml
- app/src/main/aidl/io/github/trojan_gfw/igniter/proxy/aidl/ITrojanService.aidl
- app/src/main/java/io/github/trojan_gfw/igniter/MainActivity.java
- app/src/main/java/io/github/trojan_gfw/igniter/ProxyService.java
- app/src/main/java/io/github/trojan_gfw/igniter/common/constants/Constants.java
- app/src/main/java/io/github/trojan_gfw/igniter/common/sp/CommonSP.java
- app/src/main/java/io/github/trojan_gfw/igniter/common/utils/DecodeUtils.java
- app/src/main/java/io/github/trojan_gfw/igniter/initializer/MainInitializer.java
- app/src/main/java/io/github/trojan_gfw/igniter/servers/SubscribeSettingDialog.java
- app/src/main/java/io/github/trojan_gfw/igniter/servers/activity/ServerListActivity.java
- app/src/main/java/io/github/trojan_gfw/igniter/servers/contract/ServerListContract.java
- app/src/main/java/io/github/trojan_gfw/igniter/servers/data/ServerListDataManager.java
- app/src/main/java/io/github/trojan_gfw/igniter/servers/data/ServerListDataSource.java
- app/src/main/java/io/github/trojan_gfw/igniter/servers/fragment/ServerListFragment.java
- app/src/main/java/io/github/trojan_gfw/igniter/servers/presenter/ServerListPresenter.java
- app/src/main/res/layout/dialog_subscribe_setting.xml
- app/src/main/res/menu/menu_server_list.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
- Fix the bug that debug apk and release apk cannot be installed in the same phone because of authorities clashing.
- Add server list subscription feature. Only supports the subscription in format 'TrojanURL1#remark\nTrojanURL2#remark\n...' .
> Server list Subscription feature

- app/src/main/java/io/github/trojan_gfw/igniter/MainActivity.java
Use synchronization while setting or getting trojanService in MainActivity, add null-check, fix the NullPointerException that caused by disconnecting (which leads to assigning null to trojanService).
> Fix NullPointerException in MainActivity

- app/src/main/java/io/github/trojan_gfw/igniter/servers/ItemVerticalMoveCallback.java
- app/src/main/java/io/github/trojan_gfw/igniter/servers/contract/ServerListContract.java
- app/src/main/java/io/github/trojan_gfw/igniter/servers/fragment/ServerListAdapter.java
- app/src/main/java/io/github/trojan_gfw/igniter/servers/fragment/ServerListFragment.java
- app/src/main/java/io/github/trojan_gfw/igniter/servers/presenter/ServerListPresenter.java
- app/src/main/res/menu/menu_server_list.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
Add drag item feature in ServerListFragment, user can rearrange servers in batch operation mode. Simply long click the item and drag it, rearrange the server list as you like.
> Drag item and rearrange server list feature.

- app/src/main/java/io/github/trojan_gfw/igniter/servers/data/ServerListDataManager.java
- app/src/main/java/io/github/trojan_gfw/igniter/servers/data/ServerListDataSource.java
- app/src/main/java/io/github/trojan_gfw/igniter/servers/presenter/ServerListPresenter.java
- Refine arrangement of servers from subscription. Existed config will be replaced with that from subscription. New configs would be appended to the end of the server list, ranging as is.
- Migrate data-related code from ServerListPresenter to ServerListDataManager, for single responsibility principle.
- Refine arrangement of servers from imported config file. Existed config will be replaced with that from imported config file. New configs would be appended to the end of the server list, ranging as is.
> Sorted subscription

- app/src/main/java/io/github/trojan_gfw/igniter/servers/fragment/ServerListFragment.java
Signed-off-by: imwcc <imwcc@qq.com>
> Support json files

- app/build.gradle
- app/src/main/java/io/github/trojan_gfw/igniter/servers/contract/ServerListContract.java
- app/src/main/java/io/github/trojan_gfw/igniter/servers/data/ServerListDataManager.java
- app/src/main/java/io/github/trojan_gfw/igniter/servers/data/ServerListDataSource.java
- app/src/main/java/io/github/trojan_gfw/igniter/servers/data/TrojanConfigWrapper.java
- app/src/main/java/io/github/trojan_gfw/igniter/servers/fragment/ServerListAdapter.java
- app/src/main/java/io/github/trojan_gfw/igniter/servers/fragment/ServerListFragment.java
- app/src/main/java/io/github/trojan_gfw/igniter/servers/presenter/ServerListPresenter.java
- app/src/main/res/layout/item_server.xml
- app/src/main/res/menu/menu_server_list.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
- build.gradle
Test all proxy server ping delay times.
Signed-off-by: Arvin <arvinxwang@gmail.com>
> support show ping proxy server dealy times

- app/src/main/AndroidManifest.xml
- app/src/main/java/io/github/trojan_gfw/igniter/common/app/BaseFragment.java
- app/src/main/java/io/github/trojan_gfw/igniter/qrcode/ScanQRCodeActivity.java
- app/src/main/java/io/github/trojan_gfw/igniter/qrcode/ScanQRCodeFragment.java
- app/src/main/java/io/github/trojan_gfw/igniter/servers/contract/ServerListContract.java
- app/src/main/java/io/github/trojan_gfw/igniter/servers/fragment/ServerListFragment.java
- app/src/main/java/io/github/trojan_gfw/igniter/servers/presenter/ServerListPresenter.java
- app/src/main/res/layout/activity_scan_qrcode.xml
- app/src/main/res/layout/fragment_scan_qr_code.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/arrays.xml
- app/src/main/res/values/strings.xml
- Adapt to Android 11, fix the bug that cannot get the entire installed app list.
- Add a feature that can scan QR code photo from gallery.
- Remove the useless method call of  `Fragment#setRetainInstance()` .
> Bugfix and new feature

- app/src/main/java/io/github/trojan_gfw/igniter/ProxyService.java
- app/src/main/java/io/github/trojan_gfw/igniter/common/constants/Constants.java
- app/src/main/java/io/github/trojan_gfw/igniter/common/utils/PreferenceUtils.java
- app/src/main/java/io/github/trojan_gfw/igniter/settings/contract/SettingsContract.java
- app/src/main/java/io/github/trojan_gfw/igniter/settings/data/ISettingsDataManager.java
- app/src/main/java/io/github/trojan_gfw/igniter/settings/data/SettingsDataManager.java
- app/src/main/java/io/github/trojan_gfw/igniter/settings/fragment/SettingsFragment.java
- app/src/main/java/io/github/trojan_gfw/igniter/settings/presenter/SettingsPresenter.java
- app/src/main/res/layout/fragment_settings.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
Add fixed proxy port entry in settings, disable by default. User is able to specify a fixed proxy port in allow LAN mode now.
> Specifying proxy port is now available
